version: '3.6'

services:
  database:
    container_name: db_container
    image: 'bitnami/mongodb:latest'
    volumes:
      - mongodb_data:/bitnami/mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_USERNAME=ekrresa
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=mono_db

  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - redis_data:/bitnami/redis/data
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password123

volumes:
  mongodb_data:
    driver: 'local'
  redis_data:
    driver: 'local'
